name: CI-compile

on:
  push:

jobs:
  rewrite-jsom:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: rewrite JSON
      run: |
        cd endpoints
        echo "{\"message\": \"${{ steps.slug.outputs.sha8 }}\"}">HDLBinst1.JSON
      
    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'Update entry point hash'
